// Mock provider so you can run without any external API.
export async function complete(prompt: string): Promise<{subject: string, body: string}> {
  const subject = "Re: Following up";
  const body = `Hi there,\n\nThanks for your note. Here is a dignified placeholder generated by the mock provider.\n\nBest regards,\nYour Name`;
  return { subject, body };
}
